version: '3.3'
services:
  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
#  application:
#    image: user-registration:v8
#    depends_on:
#      - mysql-db
#    environment:
#      DB_HOSTNAME: mysql-db
#      DB_PORT: 3306

volumes:
  my-db: