server:
  port: 8080

spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:${DB_PORT:3306}/user_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver




