server:
  port: 8080

spring:
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: false
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver




